### ISSUE TITLE
how to import Tom Select as ESM module in rails app with importmaps-rails gem?

### ISSUE THREAD

**Issue by adas172002** [tysongach/tom-select-rails#1]
Hi,

Just a simple question, as no JS code from Tom Select seems to be added by default. What is the correct way to use JS code created by the gem? What I tried and failed was
1. pinning tom-select in `config/importmaps.rb` `pin "tom-select", to: "tom-select-rails/js/tom-select.base.js"`
2. linking in `app/assets/config/manifets.js` 

```
//= link tom-select-rails/js/tom-select.base.js
```

and finally using Import in stimulus controller like this `import { TomSelect } from "tom-select"`, but I get an error 
`SyntaxError: The requested module 'tom-select' does not provide an export named 'TomSelect'`

**Comment by adas172002** [comment]
Just realised there are ESM specific modules avaliable, so just changing 
```
# config/importmap.rb
pin "tom-select", to: "tom-select-rails/esm/tom-select.js"
```
and
```
# app/assets/config/manifest.js
//= link tom-select-rails/esm/tom-select.js

```
works now (one needs to properly Import now with `import TomSelect from "tom-select"`)

**Comment by cimm** [comment]
I had the same problem and your issue helped me a ton. Thank you!

If you need the TomSelect plugins (like the checkbox dropdown) you can include the complete library like so:

```
# config/importmap.rb
pin "tom-select", to: "tom-select-rails/esm/tom-select.complete.js"
```

and

```
# app/assets/config/manifest.js
//= link tom-select-rails/esm/tom-select.complete.js
```
