### ISSUE TITLE
bs5 variant of tom-select.SCSS does not work with BS 5.3alpha3

### ISSUE THREAD

**Issue by adas172002** [tysongach/tom-select-rails#2]
Getting an 
```
ActionView::Template::Error (Error: argument `$color1` of `mix($color1, $color2, $weight: 50%)` must be a color
        on line 31:36 of ../../../../../.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/tom-select-rails-2.2.2/vendor/assets/stylesheets/tom-select-rails/scss/tom-select.bootstrap5.scss, in function `mix`
        from line 31:36 of ../../../../../.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/tom-select-rails-2.2.2/vendor/assets/stylesheets/tom-select-rails/scss/tom-select.bootstrap5.scss
        from line 4:9 of app/assets/stylesheets/application.scss
>> $select-color-dropdown-border-top: mix($input-border-color, $input-bg, 0.8) 
   -----------------------------------^
):
```

My assets config file:
```
# app/assets/stylesheets/application.scss
@import "bootstrap";
@import "bootstrap-icons";
@import "tom-select-rails/scss/tom-select.bootstrap5";
```
Any idea if this is due to changes in bs 5.3? I don't see any in variables related to [form-input-variables](https://github.com/twbs/bootstrap-rubygem/blob/v5.3.0.alpha3/assets/stylesheets/bootstrap/_variables.scss)

**Comment by tysongach** [comment]
As this gem is simply a wrapper around Tom Select’s asset files, I’d suggest opening an issue over in the [Tom Select repo](https://github.com/orchidjs/tom-select). That’s where the source files live and are maintained - if there’s a conflict with Bootstrap, it’ll need to get fixed there.

**Comment by adas172002** [comment]
Hello,

any plans to update gem with recent tom-select release?

**Comment by tysongach** [comment]
@adas172002 I just cut a new release 😄
